/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ca.ewert.notarytoolkotlin

import assertk.assertThat
import assertk.assertions.isTrue
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

class LibraryTest {
  @Test
  fun someLibraryMethodReturnsTrue() {
    val classUnderTest = Library()
    assertEquals(classUnderTest.someLibraryMethod(), true)
    assertThat(classUnderTest.someLibraryMethod(), name = "Test Message").isTrue()
  }
}
