/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/8.1.1/userguide/building_java_projects.html
 * This project uses @Incubating APIs which are subject to change.
 */

//
// Plugins
//
plugins {
  java
  idea
  `java-library`
  id("org.jetbrains.kotlin.jvm") version "1.8.21"
}

// Repositories for Library Dependencies
repositories {
  // Use Maven Central for resolving dependencies.
  mavenCentral()
}

// Library Dependencies
dependencies {
  // These dependencies are exported to consumers, that is to say found on their compile classpath.
  api("org.apache.commons:commons-math3:3.6.1")

  // These dependencies are used internally, and not exposed to consumers on their own compile classpath.
  implementation("com.google.guava:guava:31.1-jre")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
  toolchain {
    languageVersion.set(JavaLanguageVersion.of(17))
  }
}

testing {
  suites {
    // Configure the built-in test suite
    val test by getting(JvmTestSuite::class) {
      // Use Kotlin Test test framework
      useKotlinTest("1.8.21")
    }
  }
}


