/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ca.ewert.notarytoolkotlin

import mu.KotlinLogging

private val log = KotlinLogging.logger{}

class Library {

  fun someLibraryMethod(): Boolean {
    log.info {"Hello notarytool-kotlin"}
    return true
  }
}
