/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ca.ewert.notarytoolkotlin

import mu.KotlinLogging

private val log = KotlinLogging.logger{}

/**
 * This is a test Library Class, created by the gradle template.
 *
 * @author Victor Ewert
 */
public class Library {

  /**
   * A Test method
   *
   * @param name A name to pass in
   * @return Always returns true
   */
  public fun someLibraryMethod(name: String?): Boolean {
    log.info {"Hello notarytool-kotlin"}
    return true
  }
}
